### ISSUE TITLE
add a link to return to the course home page

### ISSUE THREAD

**Issue by Thibaut12000** [Vidalia/moodle-format_cards#13]
Learners have difficulty finding their way back to the course home page when they are in a section. Would it be possible to add a visible link so that he can find it easily?
Thanks for this great plugin.

**Comment by Vidalia** [comment]
Hi @Thibaut12000, glad to hear you're enjoying the plugin! 

There's already a lot of options for navigating back to the course home page. In the default Boost theme there's the navigation breadcrumbs at the top of the page, the "Course" button in the secondary navigation, the left-hand course index drawer, and the Cards format also gives you the option to enable the old style section navigation buttons and jump menu that also give you a link to the course main page.

I'm struggling to think of where else we can put a link to the home page. If you're using a custom theme, could you share some screenshots of what your course(s) look like?

**Comment by Thibaut12000** [comment]
Thank you for your reply. There are several ways of returning to the home page. However, the breadcrumb trail takes you either to the section or to the category, but not to the course home page (this is more of a Moodle problem).
The index in the left-hand drawer is often closed by default, so is not very visible. There's still the general "course" link, but students don't necessarily understand that it takes them to the home page.
In fact, I think I'm looking for a link to the home page as it was in the "tiles" plug-in.
![nav-plugin-cards](https://github.com/Vidalia/moodle-format_cards/assets/113307843/9514a07d-a01c-4c07-8204-87892b3d18ec)
![nav-plugin-tiles](https://github.com/Vidalia/moodle-format_cards/assets/113307843/8eb65f32-db72-4854-ad3b-4eb3fad85d57)
