### ISSUE TITLE
Cards not displaying properly in Moodle 4.4

### ISSUE THREAD

**Issue by ja15291** [Vidalia/moodle-format_cards#14]
The cards are not showing in a mobile browser (unless mobile is turned to landscaped).  This is in Moodle 4.4+ most recent build.

**Comment by Vidalia** [comment]
It looks like some of the styles that the cards format uses have disappeared between Moodle 4.3 and 4.4.

We're in the middle of a Moodle 4.4 upgrade ourselves, so I'll get a proper fix out eventually. In the meantime as a temporary solution you can add the following to your site's `additionalhtmlhead` (or the equivalent style to the extra SCSS):

```html
<style type="text/css">
@media (min-width: 840px) {
  .format-cards .dashboard-card-deck:not(.fixed-width-cards) .dashboard-card {
    width: calc(33.33% - 0.5rem);
  }
}
@media (min-width: 576px) {
  .format-cards .dashboard-card-deck:not(.fixed-width-cards) .dashboard-card {
    width: calc(50% - 0.5rem);
  }
}
.format-cards .dashboard-card-deck .dashboard-card {
  margin-bottom: .5rem;
  flex-basis: auto;
  width: 100%;
  flex-grow: 0;
  flex-shrink: 0;
}
</style>
```

**Comment by ja15291** [comment]
I can confirm that adding the code above to `additionalhtmlhead` fixes the problem.  Many thanks!
